name: Build Docker

on:
  push:
    branches:
      - "master"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t daily-note .
          docker login ghcr.io --username dracovish -p $GITHUB_TOKEN
          docker push ghcr.io/doit-boy/daily-note/daily-note:latest
          
