name: Build Docker

on:
  push:
    branches: [ "master" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t ghcr.io/doit-boy/daily-note/daily-note:latest .
          docker login ghcr.io --username dracovish -p $GITHUB_TOKEN
          docker push ghcr.io/doit-boy/daily-note/daily-note:latest
          
          docker tag ghcr.io/doit-boy/daily-note/daily-note:latest registry.cn-shanghai.aliyuncs.com/redbook-material/daily-note:latest
          docker login docker login --username=${{ secrets.ALIYUN_USERNAME }} registry.cn-shanghai.aliyuncs.com -p ${{ secrets.ALIYUN_PASSWORD }}
          docker push registry.cn-shanghai.aliyuncs.com/redbook-material/daily-note:latest
          
